name: CI for releases

on:
  push:
    branches:
      - master

jobs:
  js-install-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v18.12.1]  
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # 3.0.2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies, Test, and Build
      run: |
        cd frontend
        yarn install --frozen-lockfile --check-files
        yarn lint
        GENERATE_SOURCEMAP=false yarn build
        ls -R
      env:
        GENERATE_SOURCEMAP: false
        CI: true
    - name: Upload ReactJS Build
      uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # 3.1.0
      with:
        name: build
        path: frontend/build/

  python-install-and-test:
    runs-on: ubuntu-22.04
    env:
      PYTHON_VERSION: "3.11"

    steps:
      - name: Check out the codebase
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v3 2.5.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@2c3dd9e7e29afd70cc0950079bde6c979d1f69f9 # 4.3.1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip' # caching pip dependencies

      - name: Cache pip
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # 3.0.11
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          cd api
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
